name: food_recipe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  logger: ^1.2.0
  http: ^1.0.0
  bloc: ^8.1.4
  dio: ^5.7.0
  url_launcher: ^6.1.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  meta: ^1.15.0
  retrofit: ^4.4.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  youtube_player_flutter: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
